name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter-server=2.*
  - nbclassic=1.*
  - notebook=6.5.4
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - numpy=1.26.*
  - pandas=2.2.*
  - matplotlib=3.9.*
  - seaborn=0.13.*
  - scikit-learn=1.5.*
  - statsmodels
  - scipy
  - ipywidgets
  - openpyxl
  - lifelines=0.30.*
  - pip
  - pip:
      - ipyleaflet==0.18.2
