name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter-server=2.*        # server backend (conda, not pip)
  - nbclassic=1.*             # classic UI on Jupyter Server
  - notebook=6.5.4            # classic assets; helps nbextensions
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - numpy=1.26.*
  - pandas=2.2.*
  - matplotlib=3.9.*
  - seaborn=0.13.*
  - scikit-learn=1.5.*
  - statsmodels
  - scipy
  - ipywidgets
  - openpyxl
  - lifelines=0.30.*
  # no jupyterlab here
  # no jupyter-server via pip
  # no 'conda', 'openssl', 'sqlite' etc. (Binder provides those)
  - pip
  - pip:
      - ipyleaflet==0.18.2
      # nothing else here unless you must
